import React from 'react';
import { Loading, Spacer } from '@nextui-org/react';
import Avatars from '../src/components/avatars/Avatars';
import GifLoader from '../src/components/loaders/GifLoader';
import SearchBar from '../src/components/search/SearchBar';
import SiteContainer from '../src/components/siteContainer/SiteContainer';
import useDataAPIs from '../src/hooks/useDataAPIs';

const Home = () => {
  const { data, loading } = useDataAPIs();
  return (
    <>
      <section style={{ margin: '5em 0' }}>
        <SearchBar />
      </section>
      <main>
        {data?.length > 0 && !loading ? (
          <Avatars data={data} />
        ) : (
          data?.length > 0 &&
          loading && (
            <Loading
              type='gradient'
              size='lg'
              css={{
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
              }}
            />
          )
        )}
        {data?.length > 0 ? (
          data?.map(el => <SiteContainer key={el?.id} data={el} />)
        ) : loading ? (
          <>
            <Spacer y={2} />
            <Loading
              type='gradient'
              size='xl'
              css={{
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
              }}
            />
          </>
        ) : (
          !loading && (
            <GifLoader
              src='https://i.giphy.com/media/3o7aTskHEUdgCQAXde/giphy.webp'
              txt={
                data?.length === 0
                  ? 'No hay resultados'
                  : 'Esperando tu búsqueda'
              }
            />
          )
        )}
      </main>
    </>
  );
};

export default Home;

// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
